gems: [jekyll-paginate]
paginate: 20
root: http://horriblesoftware.com
timezone: America/Denver
defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "page"